.TH J 1
.SH NAME
j \- Joe's Screen Editor
.SH SYNOPSIS
.B j file
.br
.BR j
.SH DESCRIPTION
J is a screen editor designed to be easy to learn for novice users and
powerfull enough for experienced users.  After you invoke the editor, you can
hit ^K H ('^' mean hold the Ctrl key down while pressing the following key) to
turn on the help text.  From this you should be able to figure out how to use
the editor.  A few things need further explanation however:

J uses the "TERM" environment entry and termcap to determine the height and
width of the screen and to determine if the terminal uses scrolling regions.
Except for these differences the terminal must be ANSI/VT100 compatible.

^K J reformats the current paragraph.  ^T R can be used to change the right
margin.  The default is the width of the screen.  If auto-indent mode is set,
indented paragraphs are formated.

Use ^K B to set the beginning of a block and ^K K to set the end of a block.
You can then copy, move save or delete the marked blocsk.  To turn the
highlighting off, hit ^K B ^K K (make the beginning and ending the same or
move the beginning past the ending or move the ending before the beginning).

^K O splits a window into two.  You can then use ^K E to load a file into the
new window.  ^K I shows either one window or it shows all of the windows.  Use
^C to eliminate a window.

Control characters (0-31, 127) are shown underlined.  Characters above 127 are
shown in inverse.  You can use ` and ^\ to enter control characters
orcharacters with the 7th bit set.

Hit ^K F to find text.  You will be prompted to enter the search string.
After hitting Return, you will be prompted for options- you can type 1 or more
of:

.br
			i	Ignore case
.br
			b	Backwards
.br
			r	Replace
.br
			nnn	Find the nth occurance or do nnn replacements
.br

		If you hit r, you will also be prompted to enter the
		replacement string.

		Hit ^L to find the next occurance of the previous search
		string (with all the same options).

If for some reason J gets a signal (that it's going to crash or that the
system is messing up), it attempts to save the last file edited in a file
"aborted.j" in the current directory.

.SH FILES
.DT
.ta 25n
keymap.j			Keymap file.  J looks for this in the current
				directory, the user's home directory and in
				the directory containing J
.SH RESTRICTIONS
The file size is limited to the system process size limit

.SH BUGS
Send bug reports to rcarter@wpi.wpi.edu (Joseph H. Allen).  This should be
valid to at least January, 1991.  You can also contact me through snail mail:

.br
		Joseph H. Allen
.br
		28 Dale Lane
.br
		Smithtown, N.Y. 11787
