#!/bin/bash

FILES="history.html news.html changelog.html manpage.html index.html hints.html hacking.html capture.gif elaborate.gif cg2000.jpg trs80_16.jpg list.html options.html"

scp $FILES jhallen@shell.sourceforge.net:/home/groups/j/jo/joe-editor/htdocs

